import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const stockDir = path.join(repoRoot, 'public', 'stock');
const outFile = path.join(repoRoot, 'src', 'stockManifest.js');

function listStockFoldersWithCover() {
  if (!fs.existsSync(stockDir)) return [];
  const entries = fs.readdirSync(stockDir, { withFileTypes: true });
  const folders = [];
  for (const ent of entries) {
    if (!ent.isDirectory()) continue;
    const folder = ent.name;
    const cover = path.join(stockDir, folder, 'cover.jpg');
    if (fs.existsSync(cover)) folders.push(folder);
  }
  folders.sort((a, b) => a.localeCompare(b));
  return folders;
}

function getCover2Map(folders) {
  const map = {};
  for (const folder of folders) {
    const dir = path.join(stockDir, folder);
    const candidates = ['cover (2).jpg', 'cover(2).jpg', 'cover（2）.jpg'];
    for (const name of candidates) {
      if (fs.existsSync(path.join(dir, name))) {
        map[folder] = name;
        break;
      }
    }
  }
  return map;
}

const folders = listStockFoldersWithCover();
const cover2Map = getCover2Map(folders);

const banner = `// Auto-generated by scripts/generate_stock_manifest.mjs\n// Do not edit manually.\n`;
const body =
  `export const STOCK_FOLDERS = ${JSON.stringify(folders, null, 2)};\n\n` +
  `// Maps folderName -> preferred cover2 filename (if present)\n` +
  `export const STOCK_COVER2 = ${JSON.stringify(cover2Map, null, 2)};\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, banner + body, 'utf8');

console.log(`Wrote ${folders.length} stock folders to ${path.relative(repoRoot, outFile)}`);

