import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const stockDir = path.join(repoRoot, 'public', 'stock');
const outFile = path.join(repoRoot, 'src', 'stockManifest.js');

function listStockFoldersWithCover() {
  if (!fs.existsSync(stockDir)) return [];
  const entries = fs.readdirSync(stockDir, { withFileTypes: true });
  const folders = [];
  for (const ent of entries) {
    if (!ent.isDirectory()) continue;
    const folder = ent.name;
    const cover = path.join(stockDir, folder, 'cover.jpg');
    if (fs.existsSync(cover)) folders.push(folder);
  }
  folders.sort((a, b) => a.localeCompare(b));
  return folders;
}

const folders = listStockFoldersWithCover();

const banner = `// Auto-generated by scripts/generate_stock_manifest.mjs\n// Do not edit manually.\n`;
const body = `export const STOCK_FOLDERS = ${JSON.stringify(folders, null, 2)};\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, banner + body, 'utf8');

console.log(`Wrote ${folders.length} stock folders to ${path.relative(repoRoot, outFile)}`);

