export const cars = [
  {
    "id": 1,
    "folderName": "14 Mercedes Benz CLS250 CDI",
    "imageCount": 14,
    "title": "2014 Mercedes-Benz CLS250 CDI",
    "price": 32990,
    "mileage": 98000,
    "year": 2014,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "2.1L Turbo Diesel",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Elegant four-door coupe with premium diesel efficiency. Features stunning design, luxurious interior, and excellent highway comfort. Well maintained with full service history.",
    "features": [
      "Leather Seats",
      "Sunroof",
      "Navigation",
      "Bluetooth"
    ]
  },
  {
    "id": 2,
    "folderName": "14 Toyota Corolla",
    "imageCount": 12,
    "title": "2014 Toyota Corolla",
    "price": 14990,
    "mileage": 112000,
    "year": 2014,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Australia's best-selling sedan. Reliable, fuel-efficient, and low maintenance costs. Perfect for daily commuting and family use.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control"
    ]
  },
  {
    "id": 3,
    "folderName": "15 Honda Jazz",
    "imageCount": 14,
    "title": "2015 Honda Jazz VTi-S",
    "price": 15990,
    "mileage": 85000,
    "year": 2015,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.5L i-VTEC",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Versatile and spacious hatchback with Honda's famous Magic Seats. Excellent fuel economy and reliability. Perfect city car.",
    "features": [
      "Magic Seats",
      "Bluetooth",
      "Alloy Wheels",
      "Reverse Camera"
    ]
  },
  {
    "id": 4,
    "folderName": "16 BMW 430i GRAN COUPE MSPORT",
    "imageCount": 14,
    "title": "2016 BMW 430i Gran Coupe M Sport",
    "price": 38990,
    "mileage": 78000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Stylish four-door coupe with M Sport package. Turbocharged performance, premium interior, and head-turning design. Full BMW service history.",
    "features": [
      "M Sport Package",
      "Leather Seats",
      "Sunroof",
      "Navigation",
      "Harman Kardon"
    ]
  },
  {
    "id": 5,
    "folderName": "16 BMW X1 20i",
    "imageCount": 14,
    "title": "2016 BMW X1 sDrive20i",
    "price": 29990,
    "mileage": 82000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Compact luxury SUV with excellent driving dynamics. Spacious interior, premium features, and BMW reliability. Ideal for urban lifestyle.",
    "features": [
      "Leather Seats",
      "Navigation",
      "Parking Sensors",
      "LED Headlights"
    ]
  },
  {
    "id": 6,
    "folderName": "16 Jeep Renegade",
    "imageCount": 14,
    "title": "2016 Jeep Renegade Limited",
    "price": 22990,
    "mileage": 75000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.4L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Compact SUV with distinctive Jeep styling. Comfortable ride, good ground clearance, and modern tech features. Great for city and light off-road.",
    "features": [
      "Leather Seats",
      "Sunroof",
      "Apple CarPlay",
      "Reverse Camera"
    ]
  },
  {
    "id": 7,
    "folderName": "16 Toyota HILUX SR HI-RIDER",
    "imageCount": 14,
    "title": "2016 Toyota HiLux SR Hi-Rider",
    "price": 34990,
    "mileage": 125000,
    "year": 2016,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "2.8L Turbo Diesel",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Australia's favourite ute. Powerful diesel engine, durable build, and excellent towing capacity. Perfect for work and weekend adventures.",
    "features": [
      "Tow Bar",
      "Bluetooth",
      "Cruise Control",
      "Bull Bar"
    ]
  },
  {
    "id": 8,
    "folderName": "16 Toyota Kluger GXL",
    "imageCount": 13,
    "title": "2016 Toyota Kluger GXL AWD",
    "price": 32990,
    "mileage": 95000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.5L V6",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Spacious 7-seater family SUV with AWD capability. Smooth V6 power, excellent safety features, and Toyota reliability. Ideal for large families.",
    "features": [
      "7 Seats",
      "AWD",
      "Leather Seats",
      "Sunroof",
      "Navigation"
    ]
  },
  {
    "id": 9,
    "folderName": "16 Toyota RAV4",
    "imageCount": 12,
    "title": "2016 Toyota RAV4 GXL",
    "price": 26990,
    "mileage": 88000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Popular mid-size SUV with excellent practicality. Spacious cargo area, good fuel economy, and proven reliability. Perfect all-rounder.",
    "features": [
      "Reverse Camera",
      "Bluetooth",
      "Cruise Control",
      "Roof Rails"
    ]
  },
  {
    "id": 10,
    "folderName": "16 Volkswagen Tiguan 110 Tsi",
    "imageCount": 12,
    "title": "2016 Volkswagen Tiguan 110TSI",
    "price": 24990,
    "mileage": 79000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.4L TSI Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Stylish European SUV with efficient turbo engine. Quality interior, advanced safety, and excellent driving dynamics.",
    "features": [
      "Apple CarPlay",
      "Leather Seats",
      "Parking Sensors",
      "LED Lights"
    ]
  },
  {
    "id": 11,
    "folderName": "17 Audi A5 Quattro",
    "imageCount": 14,
    "title": "2017 Audi A5 Sportback Quattro",
    "price": 42990,
    "mileage": 68000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L TFSI",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Elegant sportback with Quattro AWD. Stunning design, premium interior, and exhilarating performance. Full Audi service history.",
    "features": [
      "Quattro AWD",
      "Virtual Cockpit",
      "Leather Seats",
      "B&O Sound",
      "Sunroof"
    ]
  },
  {
    "id": 12,
    "folderName": "17 Audi Q2",
    "imageCount": 14,
    "title": "2017 Audi Q2 Design",
    "price": 32990,
    "mileage": 55000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.4L TFSI",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Compact premium SUV with bold styling. Efficient turbo engine, quality Audi interior, and excellent city maneuverability.",
    "features": [
      "Virtual Cockpit",
      "Apple CarPlay",
      "LED Lights",
      "Parking Sensors"
    ]
  },
  {
    "id": 13,
    "folderName": "17 Jeep Compass",
    "imageCount": 14,
    "title": "2017 Jeep Compass Limited",
    "price": 26990,
    "mileage": 72000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.4L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Stylish compact SUV with Jeep DNA. Comfortable interior, modern tech, and capable off-road performance when needed.",
    "features": [
      "Leather Seats",
      "Navigation",
      "Sunroof",
      "Apple CarPlay"
    ]
  },
  {
    "id": 14,
    "folderName": "17 Kia Stonic S",
    "imageCount": 14,
    "title": "2017 Kia Stonic S",
    "price": 19990,
    "mileage": 58000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.4L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Funky compact crossover with excellent value. Stylish design, good tech features, and backed by Kia's warranty reputation.",
    "features": [
      "Apple CarPlay",
      "Reverse Camera",
      "Cruise Control",
      "Alloy Wheels"
    ]
  },
  {
    "id": 15,
    "folderName": "17 Land Rover Ranger Rover Sport 3.0 TDV6 SE",
    "imageCount": 14,
    "title": "2017 Range Rover Sport TDV6 SE",
    "price": 69990,
    "mileage": 85000,
    "year": 2017,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "3.0L V6 Turbo Diesel",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Iconic luxury SUV with commanding presence. Powerful diesel V6, premium interior, and genuine off-road capability. Full service history.",
    "features": [
      "Panoramic Roof",
      "Leather Seats",
      "Air Suspension",
      "Meridian Sound",
      "Navigation"
    ]
  },
  {
    "id": 16,
    "folderName": "17 Mercedes Benz C250",
    "imageCount": 14,
    "title": "2017 Mercedes-Benz C250",
    "price": 38990,
    "mileage": 72000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Elegant sedan with refined luxury. Smooth turbocharged performance, premium interior, and advanced safety features.",
    "features": [
      "Leather Seats",
      "Sunroof",
      "Navigation",
      "LED Lights",
      "Burmester Sound"
    ]
  },
  {
    "id": 17,
    "folderName": "17 Toyota 86 GTS",
    "imageCount": 14,
    "title": "2017 Toyota 86 GTS",
    "price": 29990,
    "mileage": 52000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L Boxer",
    "seats": 4,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Pure sports car driving experience. Rear-wheel drive, low centre of gravity, and engaging handling. Perfect weekend toy.",
    "features": [
      "Sports Seats",
      "Touchscreen",
      "Rear Spoiler",
      "18-inch Alloys"
    ]
  },
  {
    "id": 18,
    "folderName": "17 Toyota Corolla",
    "imageCount": 12,
    "title": "2017 Toyota Corolla Ascent",
    "price": 16990,
    "mileage": 78000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Reliable and economical sedan. Low running costs, proven Toyota quality, and excellent resale value. Ideal daily driver.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
      "USB Input"
    ]
  },
  {
    "id": 19,
    "folderName": "17 Volkswagen Golf 110 TSI",
    "imageCount": 14,
    "title": "2017 Volkswagen Golf 110TSI",
    "price": 22990,
    "mileage": 65000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.4L TSI Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Iconic European hatchback with quality interior. Efficient turbo engine, refined ride, and excellent build quality.",
    "features": [
      "Apple CarPlay",
      "Digital Cockpit",
      "LED Lights",
      "Parking Sensors"
    ]
  },
  {
    "id": 20,
    "folderName": "18 Ford Mustang GT 5.0",
    "imageCount": 14,
    "title": "2018 Ford Mustang GT 5.0 V8",
    "price": 54990,
    "mileage": 45000,
    "year": 2018,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "5.0L V8",
    "seats": 4,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "American muscle icon with thunderous V8 power. Iconic styling, exhilarating performance, and modern tech. Head-turner guaranteed.",
    "features": [
      "V8 Engine",
      "Leather Seats",
      "SYNC 3",
      "Performance Pack",
      "Brembo Brakes"
    ]
  },
  {
    "id": 21,
    "folderName": "19 Mercedes S450 Long Wheel Base",
    "imageCount": 14,
    "title": "2019 Mercedes-Benz S450 L",
    "price": 129990,
    "mileage": 42000,
    "year": 2019,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.0L V6 Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Flagship luxury sedan with extended wheelbase. Ultimate comfort, cutting-edge technology, and refined elegance. Chauffeur-ready.",
    "features": [
      "Executive Rear Seats",
      "Burmester 3D Sound",
      "Massage Seats",
      "Night Vision",
      "HUD"
    ]
  },
  {
    "id": 22,
    "folderName": "19 Subaru Forester",
    "imageCount": 12,
    "title": "2019 Subaru Forester 2.5i-S",
    "price": 32990,
    "mileage": 58000,
    "year": 2019,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L Boxer",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Capable all-wheel drive SUV with Subaru's renowned safety. Spacious, practical, and excellent in all weather conditions.",
    "features": [
      "EyeSight Safety",
      "Sunroof",
      "Leather Seats",
      "X-Mode AWD"
    ]
  },
  {
    "id": 23,
    "folderName": "19 Suzuki Swift Sport Edition",
    "imageCount": 14,
    "title": "2019 Suzuki Swift Sport",
    "price": 22990,
    "mileage": 48000,
    "year": 2019,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.4L Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Fun and agile hot hatch. Lightweight, turbocharged, and genuinely engaging to drive. Perfect balance of fun and practicality.",
    "features": [
      "Sports Seats",
      "Navigation",
      "Keyless Entry",
      "17-inch Alloys"
    ]
  },
  {
    "id": 24,
    "folderName": "1999 Mitsubishi Lancer Evo 6 Rally Art",
    "imageCount": 11,
    "title": "1999 Mitsubishi Lancer Evo 6 Ralliart",
    "price": 89990,
    "mileage": 125000,
    "year": 1999,
    "fuel": "Petrol",
    "transmission": "Manual",
    "engine": "2.0L Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Iconic rally legend and collector's dream. Genuine Evo 6 with turbo AWD performance. Increasingly rare and valuable JDM classic.",
    "features": [
      "Turbo AWD",
      "Recaro Seats",
      "Rally Heritage",
      "Manual Gearbox"
    ]
  },
  {
    "id": 25,
    "folderName": "20 Camry ASCENT",
    "imageCount": 14,
    "title": "2020 Toyota Camry Ascent",
    "price": 27990,
    "mileage": 45000,
    "year": 2020,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Latest generation Camry with bold design. Spacious, comfortable, and fuel-efficient. Perfect for family or business use.",
    "features": [
      "Toyota Safety Sense",
      "Apple CarPlay",
      "Reverse Camera",
      "Cruise Control"
    ]
  },
  {
    "id": 26,
    "folderName": "20 Mercedes G63",
    "imageCount": 14,
    "title": "2020 Mercedes-AMG G63",
    "price": 289990,
    "mileage": 28000,
    "year": 2020,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "4.0L V8 Biturbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Ultimate luxury off-roader with AMG power. Iconic G-Wagen design, hand-built V8, and unmatched presence. Statement vehicle.",
    "features": [
      "AMG V8 Biturbo",
      "Designo Interior",
      "Burmester Sound",
      "AMG Night Package"
    ]
  },
  {
    "id": 27,
    "folderName": "20 Toyota Corolla Hybrid",
    "imageCount": 14,
    "title": "2020 Toyota Corolla Hybrid",
    "price": 26990,
    "mileage": 52000,
    "year": 2020,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "1.8L Hybrid",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Fuel-efficient hybrid with modern design. Excellent fuel economy under 4.5L/100km, reliable Toyota hybrid system, low emissions.",
    "features": [
      "Hybrid System",
      "Toyota Safety Sense",
      "Apple CarPlay",
      "Wireless Charging"
    ]
  },
  {
    "id": 28,
    "folderName": "2004 Subaru WRX STI Manual",
    "imageCount": 13,
    "title": "2004 Subaru WRX STI",
    "price": 42990,
    "mileage": 145000,
    "year": 2004,
    "fuel": "Petrol",
    "transmission": "Manual",
    "engine": "2.5L Turbo Boxer",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Legendary rally-bred performance. Iconic blob-eye STI with symmetrical AWD and turbo power. Increasingly collectible JDM icon.",
    "features": [
      "Turbo AWD",
      "Brembo Brakes",
      "Manual 6-Speed",
      "STI Aero Kit"
    ]
  },
  {
    "id": 29,
    "folderName": "2006 Lexus LS460",
    "imageCount": 14,
    "title": "2006 Lexus LS460",
    "price": 18990,
    "mileage": 165000,
    "year": 2006,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "4.6L V8",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Flagship Lexus luxury sedan. Whisper-quiet V8, supreme comfort, and legendary Lexus reliability. Exceptional value for flagship luxury.",
    "features": [
      "Mark Levinson Sound",
      "Air Suspension",
      "Heated/Cooled Seats",
      "Sunroof"
    ]
  },
  {
    "id": 30,
    "folderName": "2006 Toyota Estima Auto",
    "imageCount": 12,
    "title": "2006 Toyota Estima",
    "price": 14990,
    "mileage": 135000,
    "year": 2006,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.4L",
    "seats": 8,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Popular 8-seater people mover. Dual power sliding doors, versatile seating, and Toyota reliability. Great family transport.",
    "features": [
      "8 Seats",
      "Dual Power Doors",
      "Rear Camera",
      "Dual Climate"
    ]
  },
  {
    "id": 31,
    "folderName": "2008 Toyota Crown Rayol Saloon",
    "imageCount": 7,
    "title": "2008 Toyota Crown Royal Saloon",
    "price": 16990,
    "mileage": 118000,
    "year": 2008,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.0L V6",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Japan's executive sedan. Smooth V6, plush interior, and exclusive JDM luxury. Unique alternative to European brands.",
    "features": [
      "V6 Engine",
      "Leather Seats",
      "Navigation",
      "Mark Levinson Sound"
    ]
  },
  {
    "id": 32,
    "folderName": "2009 Infinity G37 Auto 62315kms",
    "imageCount": 11,
    "title": "2009 Infiniti G37",
    "price": 19990,
    "mileage": 62315,
    "year": 2009,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.7L V6",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Sporty luxury coupe with powerful V6. Low kilometres for age, rear-wheel drive fun, and premium Infiniti quality.",
    "features": [
      "V6 Engine",
      "Leather Seats",
      "Bose Sound",
      "Sunroof"
    ]
  },
  {
    "id": 33,
    "folderName": "2010 Nissan Elgrand Highway Star Auto",
    "imageCount": 5,
    "title": "2010 Nissan Elgrand Highway Star",
    "price": 24990,
    "mileage": 95000,
    "year": 2010,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 8,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Premium Japanese people mover. Highway Star spec with sporty styling, dual power doors, and versatile 8-seat configuration.",
    "features": [
      "8 Seats",
      "Dual Power Doors",
      "Highway Star Kit",
      "Rear Entertainment"
    ]
  },
  {
    "id": 34,
    "folderName": "2012 Nissan Elgrand Highway Star",
    "imageCount": 13,
    "title": "2012 Nissan Elgrand Highway Star",
    "price": 29990,
    "mileage": 82000,
    "year": 2012,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 8,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Updated Elgrand with modern features. Spacious 8-seater, dual power sliding doors, and highway comfort. Popular family choice.",
    "features": [
      "8 Seats",
      "Dual Power Doors",
      "Rear Camera",
      "Climate Control"
    ]
  },
  {
    "id": 35,
    "folderName": "2013 NISSAN GTR R35 AUTO",
    "imageCount": 8,
    "title": "2013 Nissan GT-R R35",
    "price": 129990,
    "mileage": 58000,
    "year": 2013,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.8L V6 Twin Turbo",
    "seats": 4,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Legendary Godzilla supercar. Twin-turbo V6 with 550hp, AWD launch control, and supercar performance at a fraction of the cost.",
    "features": [
      "Twin Turbo V6",
      "AWD",
      "Launch Control",
      "Bose Sound",
      "Brembo Brakes"
    ]
  },
  {
    "id": 36,
    "folderName": "2014 Toyota Hiace TDI Auto",
    "imageCount": 8,
    "title": "2014 Toyota HiAce TDI",
    "price": 32990,
    "mileage": 145000,
    "year": 2014,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "3.0L Turbo Diesel",
    "seats": 12,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Workhorse van with diesel efficiency. Spacious 12-seater configuration, reliable diesel engine, and commercial-grade durability.",
    "features": [
      "12 Seats",
      "Turbo Diesel",
      "Air Conditioning",
      "High Roof"
    ]
  },
  {
    "id": 37,
    "folderName": "2015 Jaguar XE Rsport",
    "imageCount": 14,
    "title": "2015 Jaguar XE R-Sport",
    "price": 28990,
    "mileage": 78000,
    "year": 2015,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "British sports sedan with R-Sport styling. Agile handling, premium interior, and distinctive Jaguar design. Great value luxury.",
    "features": [
      "R-Sport Package",
      "Leather Seats",
      "Navigation",
      "Meridian Sound"
    ]
  },
  {
    "id": 38,
    "folderName": "2015 Lexus CT200H",
    "imageCount": 14,
    "title": "2015 Lexus CT200h F Sport",
    "price": 26990,
    "mileage": 68000,
    "year": 2015,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "1.8L Hybrid",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Luxury hybrid hatchback with F Sport styling. Excellent fuel economy, Lexus quality, and sporty driving dynamics.",
    "features": [
      "F Sport Package",
      "Hybrid System",
      "Leather Seats",
      "Mark Levinson Sound"
    ]
  },
  {
    "id": 39,
    "folderName": "2016 Honda HRV",
    "imageCount": 12,
    "title": "2016 Honda HR-V VTi-S",
    "price": 22990,
    "mileage": 72000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L i-VTEC",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Versatile compact SUV with clever Magic Seats. Good space efficiency, fuel economy, and Honda reliability.",
    "features": [
      "Magic Seats",
      "Sunroof",
      "Navigation",
      "Reverse Camera"
    ]
  },
  {
    "id": 40,
    "folderName": "2016 TOYOTA CAMRY ALTIS AUTO(4)",
    "imageCount": 9,
    "title": "2016 Toyota Camry Altise",
    "price": 18990,
    "mileage": 85000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Proven family sedan with excellent value. Spacious interior, smooth ride, and Toyota's legendary reliability.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
      "Dual Climate"
    ]
  },
  {
    "id": 41,
    "folderName": "2016 TOYOTA CAMRY ALTISE AUTO",
    "imageCount": 9,
    "title": "2016 Toyota Camry Altise",
    "price": 18490,
    "mileage": 92000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Reliable mid-size sedan with spacious cabin. Excellent fuel economy, low maintenance costs, and proven durability.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "USB Input",
      "Cruise Control"
    ]
  },
  {
    "id": 42,
    "folderName": "2016 TOYOTA CAMRY ALTISE AUTO(3)",
    "imageCount": 8,
    "title": "2016 Toyota Camry Altise",
    "price": 17990,
    "mileage": 98000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Popular family sedan at exceptional value. Smooth and comfortable drive, practical interior, Toyota quality assured.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control"
    ]
  },
  {
    "id": 43,
    "folderName": "2016 TOYOTA CAMRY HYBRID CVT",
    "imageCount": 8,
    "title": "2016 Toyota Camry Hybrid",
    "price": 22990,
    "mileage": 78000,
    "year": 2016,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Fuel-efficient hybrid sedan with excellent economy. Under 5L/100km, smooth CVT, and Toyota hybrid reliability proven over millions of km.",
    "features": [
      "Hybrid System",
      "Bluetooth",
      "Reverse Camera",
      "Eco Mode"
    ]
  },
  {
    "id": 44,
    "folderName": "2016 TOYOTA COROLLA ASCENT SPORT CVT-S",
    "imageCount": 12,
    "title": "2016 Toyota Corolla Ascent Sport",
    "price": 17990,
    "mileage": 82000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Sporty-styled Corolla with alloy wheels and bodykit. Reliable 1.8L engine, excellent fuel economy, and Toyota quality.",
    "features": [
      "Sport Bodykit",
      "Alloy Wheels",
      "Reverse Camera",
      "Bluetooth"
    ]
  },
  {
    "id": 45,
    "folderName": "2016 Toyota Alphard EL Hybrid",
    "imageCount": 13,
    "title": "2016 Toyota Alphard Executive Lounge Hybrid",
    "price": 79990,
    "mileage": 65000,
    "year": 2016,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Top-of-the-line Alphard with Executive Lounge seats. Ultimate luxury MPV with hybrid efficiency, massage seats, and first-class comfort.",
    "features": [
      "Executive Lounge Seats",
      "Hybrid AWD",
      "Massage Seats",
      "JBL Sound",
      "Ottomans"
    ]
  },
  {
    "id": 46,
    "folderName": "2016 Toyota Alphard GF Hybrid Auto",
    "imageCount": 14,
    "title": "2016 Toyota Alphard GF Hybrid",
    "price": 69990,
    "mileage": 72000,
    "year": 2016,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Premium Alphard GF grade with hybrid powertrain. Luxurious captain seats, excellent fuel economy, and sophisticated technology.",
    "features": [
      "Captain Seats",
      "Hybrid AWD",
      "JBL Sound",
      "Power Tailgate",
      "Sunroof"
    ]
  },
  {
    "id": 47,
    "folderName": "2016 Toyota Alphard GF V6 Auto",
    "imageCount": 13,
    "title": "2016 Toyota Alphard GF 3.5 V6",
    "price": 64990,
    "mileage": 68000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.5L V6",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Powerful V6 Alphard with smooth acceleration. Premium GF grade with luxurious interior, ideal for those preferring petrol power.",
    "features": [
      "V6 Engine",
      "Captain Seats",
      "JBL Sound",
      "Power Tailgate"
    ]
  },
  {
    "id": 48,
    "folderName": "2016 Toyota Alphard SRC Hybrid AWD",
    "imageCount": 14,
    "title": "2016 Toyota Alphard SC Hybrid AWD",
    "price": 62990,
    "mileage": 75000,
    "year": 2016,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Sporty SC grade Alphard with hybrid AWD. Aggressive styling, efficient drivetrain, and all-weather capability.",
    "features": [
      "Hybrid AWD",
      "Captain Seats",
      "Aero Kit",
      "Power Doors"
    ]
  },
  {
    "id": 49,
    "folderName": "2016 Toyota Alphard SRC With JBL",
    "imageCount": 8,
    "title": "2016 Toyota Alphard SC with JBL",
    "price": 58990,
    "mileage": 82000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "SC grade Alphard with premium JBL sound system. Sporty styling, captain seats, and concert-quality audio experience.",
    "features": [
      "JBL Premium Sound",
      "Captain Seats",
      "Power Doors",
      "Reverse Camera"
    ]
  },
  {
    "id": 50,
    "folderName": "2016 Toyota Alphard SRC with Body kit",
    "imageCount": 14,
    "title": "2016 Toyota Alphard SC Aero",
    "price": 59990,
    "mileage": 78000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "SC Alphard with aggressive aero body kit. Head-turning styling, premium comfort, and distinctive road presence.",
    "features": [
      "Aero Body Kit",
      "Captain Seats",
      "Power Doors",
      "LED Lights"
    ]
  },
  {
    "id": 51,
    "folderName": "2016 Toyota Camry Altise Auto(1)",
    "imageCount": 12,
    "title": "2016 Toyota Camry Altise",
    "price": 18290,
    "mileage": 88000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Well-maintained Camry with full service history. Reliable family sedan with excellent comfort and Toyota quality.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
      "Dual Climate"
    ]
  },
  {
    "id": 52,
    "folderName": "2016 Toyota Camry Altise Auto(2)",
    "imageCount": 10,
    "title": "2016 Toyota Camry Altise",
    "price": 17790,
    "mileage": 95000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Affordable quality sedan with proven reliability. Comfortable highway cruiser with low running costs.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control"
    ]
  },
  {
    "id": 53,
    "folderName": "2016 Toyota Camry Altise Auto(5)",
    "imageCount": 9,
    "title": "2016 Toyota Camry Altise",
    "price": 17490,
    "mileage": 102000,
    "year": 2016,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Excellent value Camry ready for new owner. Smooth and reliable, perfect for daily commuting or family use.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control"
    ]
  },
  {
    "id": 54,
    "folderName": "2016 Toyota Camry Altise Hybrid",
    "imageCount": 7,
    "title": "2016 Toyota Camry Hybrid",
    "price": 21990,
    "mileage": 82000,
    "year": 2016,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Economical hybrid sedan with proven technology. Great fuel savings, smooth drive, and environmentally conscious choice.",
    "features": [
      "Hybrid System",
      "Bluetooth",
      "Reverse Camera",
      "Eco Mode"
    ]
  },
  {
    "id": 55,
    "folderName": "2016 Toyota Vellfire Hybrid Auto",
    "imageCount": 12,
    "title": "2016 Toyota Vellfire Hybrid",
    "price": 64990,
    "mileage": 70000,
    "year": 2016,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Sporty Vellfire with hybrid efficiency. Bold front styling, luxurious interior, and excellent fuel economy for a large MPV.",
    "features": [
      "Hybrid AWD",
      "Captain Seats",
      "Power Doors",
      "JBL Sound"
    ]
  },
  {
    "id": 56,
    "folderName": "2017 Honda odyssey high spec",
    "imageCount": 14,
    "title": "2017 Honda Odyssey VTi-L",
    "price": 34990,
    "mileage": 68000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.4L i-VTEC",
    "seats": 8,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "High-spec 8-seater people mover. Spacious cabin, Honda reliability, and versatile seating configurations.",
    "features": [
      "8 Seats",
      "Leather Interior",
      "Sunroof",
      "Honda Sensing",
      "Power Tailgate"
    ]
  },
  {
    "id": 57,
    "folderName": "2017 Mercedes Benz C200 Auto",
    "imageCount": 7,
    "title": "2017 Mercedes-Benz C200",
    "price": 36990,
    "mileage": 75000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Elegant entry luxury sedan with Mercedes quality. Refined driving experience, premium interior, modern tech features.",
    "features": [
      "Leather Seats",
      "Navigation",
      "LED Lights",
      "Parking Assist"
    ]
  },
  {
    "id": 58,
    "folderName": "2017 TOYOTA COROLLA ASENT SEDAN CVT",
    "imageCount": 13,
    "title": "2017 Toyota Corolla Ascent",
    "price": 16490,
    "mileage": 75000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Reliable Corolla sedan with proven quality. Excellent fuel economy, low maintenance, and strong resale value.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
      "USB Input"
    ]
  },
  {
    "id": 59,
    "folderName": "2017 Tiguan 132 2.0 TSI",
    "imageCount": 14,
    "title": "2017 Volkswagen Tiguan 132TSI",
    "price": 29990,
    "mileage": 72000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L TSI Turbo",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Powerful turbo SUV with European refinement. Strong 2.0 TSI engine, quality interior, and excellent driving dynamics.",
    "features": [
      "Apple CarPlay",
      "Digital Cockpit",
      "Leather Seats",
      "Panoramic Roof"
    ]
  },
  {
    "id": 60,
    "folderName": "2017 Toyota Camry Alties Auto",
    "imageCount": 9,
    "title": "2017 Toyota Camry Altise",
    "price": 19990,
    "mileage": 72000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Dependable family sedan with excellent value. Comfortable ride, spacious interior, and proven Toyota reliability.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
      "Dual Climate"
    ]
  },
  {
    "id": 61,
    "folderName": "2017 Toyota Camry Atara SL",
    "imageCount": 12,
    "title": "2017 Toyota Camry Atara SL",
    "price": 24990,
    "mileage": 68000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Top-spec Camry with premium features. Leather interior, JBL sound, and advanced safety suite. Luxury without luxury pricing.",
    "features": [
      "Leather Seats",
      "JBL Sound",
      "Sunroof",
      "Toyota Safety Sense"
    ]
  },
  {
    "id": 62,
    "folderName": "2017 Toyota Camry Auto Navi",
    "imageCount": 12,
    "title": "2017 Toyota Camry SX",
    "price": 22990,
    "mileage": 70000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Well-equipped Camry with satellite navigation. Comfortable highway cruiser with modern tech and Toyota quality.",
    "features": [
      "Navigation",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control"
    ]
  },
  {
    "id": 63,
    "folderName": "2017 Toyota Corolla Ascent CVT",
    "imageCount": 12,
    "title": "2017 Toyota Corolla Ascent",
    "price": 16990,
    "mileage": 72000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Australia's favourite small car. Reliable, economical, and low maintenance. Ideal first car or daily commuter.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
      "USB Input"
    ]
  },
  {
    "id": 64,
    "folderName": "2017 Toyota Corolla Ascent CVT(2)",
    "imageCount": 11,
    "title": "2017 Toyota Corolla Ascent",
    "price": 16490,
    "mileage": 78000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Well-maintained Corolla ready for new owner. Smooth CVT, excellent fuel economy, and proven reliability.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control"
    ]
  },
  {
    "id": 65,
    "folderName": "2017 Toyota Corolla Ascent CVT(3)",
    "imageCount": 11,
    "title": "2017 Toyota Corolla Ascent",
    "price": 15990,
    "mileage": 82000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Great value Corolla with full service history. Economical daily driver with Toyota's legendary reliability.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control"
    ]
  },
  {
    "id": 66,
    "folderName": "2017 Toyota Corrola Ascent Auto",
    "imageCount": 13,
    "title": "2017 Toyota Corolla Ascent",
    "price": 16290,
    "mileage": 76000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Popular small sedan with excellent ownership experience. Low running costs and strong resale value.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
      "USB Input"
    ]
  },
  {
    "id": 67,
    "folderName": "2017 Toyota Yaris Auto 40000kms",
    "imageCount": 10,
    "title": "2017 Toyota Yaris",
    "price": 14990,
    "mileage": 40000,
    "year": 2017,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.3L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Low kilometre Yaris - perfect city car. Compact size, easy parking, and Toyota reliability. Exceptional value.",
    "features": [
      "Bluetooth",
      "Reverse Camera",
      "USB Input"
    ]
  },
  {
    "id": 68,
    "folderName": "2019 BMW 840d Msport",
    "imageCount": 14,
    "title": "2019 BMW 840d M Sport",
    "price": 119990,
    "mileage": 48000,
    "year": 2019,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "3.0L Turbo Diesel",
    "seats": 4,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Stunning grand tourer with diesel efficiency. M Sport package, luxurious interior, and effortless highway cruising.",
    "features": [
      "M Sport Package",
      "Harman Kardon",
      "Laser Lights",
      "Gesture Control",
      "HUD"
    ]
  },
  {
    "id": 69,
    "folderName": "2019 BMW X5 30d",
    "imageCount": 14,
    "title": "2019 BMW X5 xDrive30d",
    "price": 79990,
    "mileage": 55000,
    "year": 2019,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "3.0L Turbo Diesel",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Luxury SUV with diesel efficiency. Latest generation X5 with impressive tech, refined comfort, and capable AWD.",
    "features": [
      "xDrive AWD",
      "Panoramic Roof",
      "Leather Seats",
      "Harman Kardon",
      "Air Suspension"
    ]
  },
  {
    "id": 70,
    "folderName": "2019 New Toyota Alphard SC Auto",
    "imageCount": 14,
    "title": "2019 Toyota Alphard SC",
    "price": 72990,
    "mileage": 45000,
    "year": 2019,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Sporty SC grade Alphard with modern features. Aggressive styling, premium comfort, and excellent family transport.",
    "features": [
      "Captain Seats",
      "Power Doors",
      "Toyota Safety Sense",
      "JBL Sound"
    ]
  },
  {
    "id": 71,
    "folderName": "2019 Toyota Alphard GF Auto Brand New",
    "imageCount": 12,
    "title": "2019 Toyota Alphard GF",
    "price": 78990,
    "mileage": 32000,
    "year": 2019,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Premium GF grade Alphard with low kilometres. Luxurious captain seats, premium JBL audio, excellent condition.",
    "features": [
      "Captain Seats",
      "JBL Sound",
      "Power Tailgate",
      "Sunroof",
      "Power Doors"
    ]
  },
  {
    "id": 72,
    "folderName": "2019 Toyota Kluger 7seats",
    "imageCount": 12,
    "title": "2019 Toyota Kluger GXL 7-Seater",
    "price": 42990,
    "mileage": 62000,
    "year": 2019,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.5L V6",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Spacious 7-seat family SUV with V6 power. Toyota Safety Sense, comfortable ride, and excellent family practicality.",
    "features": [
      "7 Seats",
      "Toyota Safety Sense",
      "Leather Seats",
      "Sunroof",
      "Navigation"
    ]
  },
  {
    "id": 73,
    "folderName": "2020 Toyota Alphard GF 3.5 V6 New Car",
    "imageCount": 4,
    "title": "2020 Toyota Alphard GF 3.5 V6",
    "price": 89990,
    "mileage": 18000,
    "year": 2020,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.5L V6",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Near-new Alphard with powerful V6. Ultra-low kilometres, premium GF spec, and like-new condition. Exceptional opportunity.",
    "features": [
      "V6 Engine",
      "Captain Seats",
      "JBL Sound",
      "Power Tailgate",
      "Sunroof"
    ]
  },
  {
    "id": 74,
    "folderName": "2021 Honda Civic VTI",
    "imageCount": 14,
    "title": "2021 Honda Civic VTi",
    "price": 28990,
    "mileage": 38000,
    "year": 2021,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "1.8L i-VTEC",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "All-new generation Civic with bold styling. Excellent driving dynamics, quality interior, and Honda reliability.",
    "features": [
      "Honda Sensing",
      "Apple CarPlay",
      "LED Lights",
      "Lane Keep Assist"
    ]
  },
  {
    "id": 75,
    "folderName": "2021 Toyota Kluger Grande 7-Seater",
    "imageCount": 14,
    "title": "2021 Toyota Kluger Grande AWD",
    "price": 62990,
    "mileage": 42000,
    "year": 2021,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.5L V6",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Top-spec Kluger with all the features. Luxurious Grande trim, V6 power, and 7-seat practicality. Flagship family SUV.",
    "features": [
      "7 Seats",
      "AWD",
      "JBL Sound",
      "Panoramic Roof",
      "Ventilated Seats"
    ]
  },
  {
    "id": 76,
    "folderName": "2023 Toyota Alphard 2.5L",
    "imageCount": 14,
    "title": "2023 Toyota Alphard 2.5L",
    "price": 98990,
    "mileage": 15000,
    "year": 2023,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Latest generation 40-series Alphard. Brand new design, advanced tech, and ultimate luxury. Very low kilometres.",
    "features": [
      "New 40-Series",
      "Captain Seats",
      "12.3-inch Display",
      "Toyota Safety Sense 3.0"
    ]
  },
  {
    "id": 77,
    "folderName": "2024 Toyota Vellfire",
    "imageCount": 13,
    "title": "2024 Toyota Vellfire",
    "price": 106800,
    "mileage": 4337,
    "year": 2024,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Latest 40-series Vellfire with bold styling. Ultra-modern interior, hybrid efficiency, and distinctive Vellfire design.",
    "features": [
      "New 40-Series",
      "Hybrid",
      "Captain Seats",
      "14-inch Display",
      "Digital Key"
    ],
    "coverUrl": "https://www.auto-home.com.au/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqhfubdsu%2Fimage%2Fupload%2Fv1764262171%2Fautohome_website_production%2F1493_1.jpg&amp;w=750&amp;q=75",
    "source": "https://www.auto-home.com.au/showroom/toyota-alphard-vellfire",
    "sourceDetailUrl": "https://www.auto-home.com.au/car-detail/1493"
  },
  {
    "id": 78,
    "folderName": "2024 Toyota Voxy (BRAND NEW)",
    "imageCount": 14,
    "title": "2024 Toyota Voxy",
    "price": 58990,
    "mileage": 50,
    "year": 2024,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L",
    "seats": 8,
    "color": "White",
    "location": "Homebush",
    "status": "Brand New",
    "description": "Brand new Voxy - affordable luxury MPV. Spacious 8-seater, modern styling, and excellent value proposition.",
    "features": [
      "8 Seats",
      "Power Doors",
      "Toyota Safety Sense",
      "Digital Display"
    ]
  },
  {
    "id": 79,
    "folderName": "2025 Toyota Voxy (BRAND NEW)",
    "imageCount": 14,
    "title": "2025 Toyota Voxy",
    "price": 62990,
    "mileage": 10,
    "year": 2025,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.0L",
    "seats": 8,
    "color": "White",
    "location": "Homebush",
    "status": "Brand New",
    "description": "Latest 2025 model Voxy. Factory fresh with full warranty, spacious 8-seater with modern tech and Toyota quality.",
    "features": [
      "8 Seats",
      "Power Doors",
      "Toyota Safety Sense",
      "Wireless Charging"
    ]
  },
  {
    "id": 80,
    "folderName": "21 BMW X5 30D Msport",
    "imageCount": 0,
    "title": "2021 BMW X5 xDrive30d M Sport",
    "price": 98990,
    "mileage": 45000,
    "year": 2021,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "3.0L Turbo Diesel",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Flagship luxury SUV with M Sport styling. Powerful diesel, cutting-edge tech, and commanding presence.",
    "features": [
      "M Sport Package",
      "Air Suspension",
      "Panoramic Roof",
      "Harman Kardon",
      "Gesture Control"
    ]
  },
  {
    "id": 81,
    "folderName": "21 Mazda CX-8",
    "imageCount": 14,
    "title": "2021 Mazda CX-8 GT",
    "price": 46990,
    "mileage": 48000,
    "year": 2021,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "2.2L Turbo Diesel",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Premium 7-seater SUV with Mazda quality. Stylish design, refined interior, and efficient diesel engine.",
    "features": [
      "7 Seats",
      "Leather Interior",
      "Sunroof",
      "Bose Sound",
      "360 Camera"
    ]
  },
  {
    "id": 82,
    "folderName": "21 Toyota Alphard",
    "imageCount": 14,
    "title": "2021 Toyota Alphard SC",
    "price": 82990,
    "mileage": 38000,
    "year": 2021,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Low kilometre Alphard in excellent condition. Sporty SC spec with modern safety features and premium comfort.",
    "features": [
      "Captain Seats",
      "Power Doors",
      "Toyota Safety Sense",
      "JBL Sound"
    ]
  },
  {
    "id": 83,
    "folderName": "21 Toyota Camry Ascent",
    "imageCount": 13,
    "title": "2021 Toyota Camry Ascent",
    "price": 29990,
    "mileage": 42000,
    "year": 2021,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Current generation Camry with TNGA platform. Improved dynamics, modern design, and Toyota Safety Sense standard.",
    "features": [
      "Toyota Safety Sense",
      "Apple CarPlay",
      "Reverse Camera",
      "Adaptive Cruise"
    ]
  },
  {
    "id": 84,
    "folderName": "22 Mazda CX5 Touring",
    "imageCount": 14,
    "title": "2022 Mazda CX-5 Touring",
    "price": 38990,
    "mileage": 35000,
    "year": 2022,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "2.5L",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Stylish mid-size SUV with premium feel. Excellent driving dynamics, quality interior, and Mazda reliability.",
    "features": [
      "Leather Seats",
      "Bose Sound",
      "Sunroof",
      "i-Activsense Safety"
    ]
  },
  {
    "id": 85,
    "folderName": "22 Tesla Model 3",
    "imageCount": 14,
    "title": "2022 Tesla Model 3 Long Range",
    "price": 52990,
    "mileage": 28000,
    "year": 2022,
    "fuel": "Electric",
    "transmission": "Auto",
    "engine": "Dual Motor Electric",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Premium electric sedan with impressive range. Instant acceleration, minimalist interior, and free Supercharger network access.",
    "features": [
      "Dual Motor AWD",
      "Autopilot",
      "15-inch Touchscreen",
      "Premium Audio",
      "Glass Roof"
    ]
  },
  {
    "id": 86,
    "folderName": "22 Toyota RAV4 Cruiser Hybrid",
    "imageCount": 14,
    "title": "2022 Toyota RAV4 Cruiser Hybrid",
    "price": 52990,
    "mileage": 32000,
    "year": 2022,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Top-spec RAV4 with hybrid efficiency. Full luxury features, excellent fuel economy, and Toyota reliability.",
    "features": [
      "Hybrid AWD",
      "JBL Sound",
      "Leather Seats",
      "Panoramic Roof",
      "360 Camera"
    ]
  },
  {
    "id": 87,
    "folderName": "23 BYD Dolphin Premium",
    "imageCount": 14,
    "title": "2023 BYD Dolphin Premium",
    "price": 38990,
    "mileage": 12000,
    "year": 2023,
    "fuel": "Electric",
    "transmission": "Auto",
    "engine": "Electric Motor",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Popular electric hatchback with great value. Blade battery technology, stylish design, and impressive range.",
    "features": [
      "Electric",
      "Rotating Screen",
      "Vehicle-to-Load",
      "360 Camera"
    ]
  },
  {
    "id": 88,
    "folderName": "23 Toyota Corolla Hybrid",
    "imageCount": 14,
    "title": "2023 Toyota Corolla Hybrid",
    "price": 32990,
    "mileage": 18000,
    "year": 2023,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "1.8L Hybrid",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Latest Corolla Hybrid with excellent fuel economy. Modern safety features, quality interior, and proven hybrid technology.",
    "features": [
      "Hybrid System",
      "Toyota Safety Sense 3.0",
      "Wireless Charging",
      "12.3-inch Display"
    ]
  },
  {
    "id": 89,
    "folderName": "24 Ford Ranger Raptor",
    "imageCount": 14,
    "title": "2024 Ford Ranger Raptor",
    "price": 89990,
    "mileage": 8000,
    "year": 2024,
    "fuel": "Diesel",
    "transmission": "Auto",
    "engine": "3.0L V6 Turbo Diesel",
    "seats": 5,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Ultimate performance ute with V6 power. Off-road suspension, aggressive styling, and serious capability.",
    "features": [
      "V6 Turbo Diesel",
      "Fox Suspension",
      "12-inch Screen",
      "B&O Sound",
      "Terrain Modes"
    ]
  },
  {
    "id": 90,
    "folderName": "24 Toyota Vellfire 2.5L Hybrid",
    "imageCount": 12,
    "title": "2024 Toyota Vellfire 2.5L Hybrid",
    "price": 118990,
    "mileage": 5000,
    "year": 2024,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Near-new 40-series Vellfire Hybrid. Bold design, efficient hybrid system, and outstanding luxury. Barely driven.",
    "features": [
      "New 40-Series",
      "Hybrid",
      "Executive Seats",
      "14-inch Display",
      "Digital Key"
    ]
  },
  {
    "id": 91,
    "folderName": "24 Toyota Vellfire Hybrid",
    "imageCount": 14,
    "title": "2024 Toyota Vellfire Hybrid",
    "price": 125990,
    "mileage": 3500,
    "year": 2024,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Premium Vellfire Hybrid - delivery kilometres only. Factory warranty, ultimate luxury MPV with latest technology.",
    "features": [
      "New 40-Series",
      "Hybrid AWD",
      "Premium Audio",
      "Ottoman Seats",
      "Ambient Lighting"
    ]
  },
  {
    "id": 92,
    "folderName": "25 Toyota Vellfire",
    "imageCount": 14,
    "title": "2025 Toyota Vellfire",
    "price": 132990,
    "mileage": 500,
    "year": 2025,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "Brand New",
    "description": "Brand new 2025 Vellfire - latest model year. Full factory warranty, ultimate luxury specification. Immediate delivery.",
    "features": [
      "2025 Model",
      "Hybrid AWD",
      "Executive Package",
      "Premium Sound",
      "Advanced Safety"
    ]
  },
  {
    "id": 93,
    "folderName": "25 Toyota Vellfire Executive Lounge",
    "imageCount": 14,
    "title": "2025 Toyota Vellfire Executive Lounge",
    "price": 168990,
    "mileage": 200,
    "year": 2025,
    "fuel": "Hybrid",
    "transmission": "Auto",
    "engine": "2.5L Hybrid",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "Brand New",
    "description": "Ultimate Vellfire - Executive Lounge specification. First-class airline comfort, massage seats, and pinnacle of luxury MPVs.",
    "features": [
      "Executive Lounge",
      "Massage Seats",
      "Ottomans",
      "JBL Premium",
      "Wood Trim"
    ]
  },
  {
    "id": 94,
    "folderName": "New 2019 Toyota Alphard SC 3.5 Auto",
    "imageCount": 6,
    "title": "2019 Toyota Alphard SC 3.5 V6",
    "price": 74990,
    "mileage": 28000,
    "year": 2019,
    "fuel": "Petrol",
    "transmission": "Auto",
    "engine": "3.5L V6",
    "seats": 7,
    "color": "White",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Low kilometre V6 Alphard with powerful engine. SC sport styling, premium features, and excellent condition.",
    "features": [
      "V6 Engine",
      "Captain Seats",
      "Aero Kit",
      "Power Doors",
      "JBL Sound"
    ]
  },
  {
    "id": 95,
    "folderName": "",
    "imageCount": 0,
    "title": "2024 Toyota Alphard",
    "price": 89800,
    "mileage": 15,
    "year": 2024,
    "fuel": "",
    "transmission": "Auto",
    "engine": "",
    "seats": 7,
    "color": "",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Enquire for full vehicle details. 车辆详情欢迎咨询。",
    "features": [],
    "coverUrl": "https://www.auto-home.com.au/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqhfubdsu%2Fimage%2Fupload%2Fv1755321398%2Fautohome_website_production%2F778_1.jpg&amp;w=750&amp;q=75",
    "source": "https://www.auto-home.com.au/showroom/toyota-alphard-vellfire",
    "sourceDetailUrl": "https://www.auto-home.com.au/car-detail/778"
  },
  {
    "id": 97,
    "folderName": "",
    "imageCount": 0,
    "title": "2024 Toyota Alphard",
    "price": 109900,
    "mileage": 107,
    "year": 2024,
    "fuel": "",
    "transmission": "Auto",
    "engine": "",
    "seats": 7,
    "color": "",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Enquire for full vehicle details. 车辆详情欢迎咨询。",
    "features": [],
    "coverUrl": "https://www.auto-home.com.au/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqhfubdsu%2Fimage%2Fupload%2Fv1766075892%2Fautohome_website_production%2F1498_1.jpg&amp;w=750&amp;q=75",
    "source": "https://www.auto-home.com.au/showroom/toyota-alphard-vellfire",
    "sourceDetailUrl": "https://www.auto-home.com.au/car-detail/1498"
  },
  {
    "id": 100,
    "folderName": "",
    "imageCount": 0,
    "title": "2024 Toyota Alphard",
    "price": 87800,
    "mileage": 7312,
    "year": 2024,
    "fuel": "",
    "transmission": "Auto",
    "engine": "",
    "seats": 7,
    "color": "",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Enquire for full vehicle details. 车辆详情欢迎咨询。",
    "features": [],
    "coverUrl": "https://www.auto-home.com.au/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqhfubdsu%2Fimage%2Fupload%2Fv1756209605%2Fautohome_website_production%2F1349_1.jpg&amp;w=750&amp;q=75",
    "source": "https://www.auto-home.com.au/showroom/toyota-alphard-vellfire",
    "sourceDetailUrl": "https://www.auto-home.com.au/car-detail/1349"
  },
  {
    "id": 104,
    "folderName": "",
    "imageCount": 0,
    "title": "2024 Toyota Alphard",
    "price": 96800,
    "mileage": 7755,
    "year": 2024,
    "fuel": "",
    "transmission": "Auto",
    "engine": "",
    "seats": 7,
    "color": "",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Enquire for full vehicle details. 车辆详情欢迎咨询。",
    "features": [],
    "coverUrl": "https://www.auto-home.com.au/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqhfubdsu%2Fimage%2Fupload%2Fv1763050444%2Fautohome_website_production%2F1337_1.jpg&amp;w=750&amp;q=75",
    "source": "https://www.auto-home.com.au/showroom/toyota-alphard-vellfire",
    "sourceDetailUrl": "https://www.auto-home.com.au/car-detail/1337"
  },
  {
    "id": 109,
    "folderName": "",
    "imageCount": 0,
    "title": "2023 Toyota Alphard",
    "price": 94800,
    "mileage": 5500,
    "year": 2023,
    "fuel": "",
    "transmission": "Auto",
    "engine": "",
    "seats": 7,
    "color": "",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Enquire for full vehicle details. 车辆详情欢迎咨询。",
    "features": [],
    "coverUrl": "https://www.auto-home.com.au/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqhfubdsu%2Fimage%2Fupload%2Fv1755321531%2Fautohome_website_production%2F921_1.jpg&amp;w=750&amp;q=75",
    "source": "https://www.auto-home.com.au/showroom/toyota-alphard-vellfire",
    "sourceDetailUrl": "https://www.auto-home.com.au/car-detail/921"
  },
  {
    "id": 115,
    "folderName": "",
    "imageCount": 0,
    "title": "2023 Toyota Vellfire",
    "price": 101800,
    "mileage": 6087,
    "year": 2023,
    "fuel": "",
    "transmission": "Auto",
    "engine": "",
    "seats": 7,
    "color": "",
    "location": "Homebush",
    "status": "In Stock",
    "description": "Enquire for full vehicle details. 车辆详情欢迎咨询。",
    "features": [],
    "coverUrl": "https://www.auto-home.com.au/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqhfubdsu%2Fimage%2Fupload%2Fv1755323049%2Fautohome_website_production%2F1336_1.jpg&amp;w=750&amp;q=75",
    "source": "https://www.auto-home.com.au/showroom/toyota-alphard-vellfire",
    "sourceDetailUrl": "https://www.auto-home.com.au/car-detail/1336"
  }
];
